on:
  push:
    branches-ignore:
      - "**"

name: Upload DAGs to S3

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: <AWS_REGION>

      - name: upload to s3
        id: s3-sync
        run: |
          aws s3 sync . s3://<BUCKET_NAME> \
          --delete \
          --exclude "*" \
          --include "airflow_dags/*" \
          --include "dbt_dags/*"
